"""add external_id to car

Revision ID: e2087a496178
Revises: 7ae688a2f26b
Create Date: 2026-01-03 11:34:22.679026

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e2087a496178"
down_revision: Union[str, Sequence[str], None] = "7ae688a2f26b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cars", sa.Column("external_id", sa.String(), nullable=True))
    op.create_index(op.f("ix_cars_external_id"), "cars", ["external_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cars_external_id"), table_name="cars")
    op.drop_column("cars", "external_id")
    # ### end Alembic commands ###
