"""add url in car_image

Revision ID: ff3cc2ae1f32
Revises: e2087a496178
Create Date: 2026-01-03 11:57:50.869898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff3cc2ae1f32'
down_revision: Union[str, Sequence[str], None] = 'e2087a496178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_images', sa.Column('url', sa.String(), nullable=False))
    op.alter_column('car_images', 'path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('car_images', 'path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('car_images', 'url')
    # ### end Alembic commands ###
